[project]
name = "city-landscape-change"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "earthengine-api>=1.7.40",
    "geemap>=0.38.3",
    "geopandas>=1.1.4",
    "pyarrow>=25.0.1",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-recording>=0.13.4",
    "ruff>=0.16.3",
]
